<?php

namespace Database\Seeders;

use App\Models\Tourism;
use Illuminate\Database\Seeder;

class TourismSeeder extends Seeder
{
    public function run(): void
    {
        $tourismData = [
            [
                'name' => 'Candi Borobudur',
                'description' => 'Candi Buddha terbesar di dunia dan situs warisan dunia UNESCO. Dibangun pada abad ke-8 dan ke-9, Borobudur merupakan salah satu keajaiban arsitektur kuno yang menakjubkan.',
                'address' => 'Jl. Badrawati, Borobudur',
                'city' => 'Magelang',
                'category' => 'Sejarah & Budaya',
                'image' => 'https://images.unsplash.com/photo-1555400082-8c5cd5b3c3e1?w=600',
                'rating' => 4.8,
                'total_reviews' => 2500,
                'entrance_fee' => 50000,
                'opening_hours_start' => '06:00:00',
                'opening_hours_end' => '17:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Mushola', 'Restoran', 'Toko Souvenir'],
                'latitude' => -7.6079,
                'longitude' => 110.2038,
            ],
            [
                'name' => 'Lawang Sewu',
                'description' => 'Bangunan bersejarah peninggalan kolonial Belanda yang terkenal dengan arsitektur yang memukau dan cerita mistisnya.',
                'address' => 'Jl. Pemuda, Sekayu',
                'city' => 'Semarang',
                'category' => 'Sejarah & Budaya',
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600',
                'rating' => 4.5,
                'total_reviews' => 1800,
                'entrance_fee' => 10000,
                'opening_hours_start' => '08:00:00',
                'opening_hours_end' => '16:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Mushola', 'Cafe'],
                'latitude' => -6.9666,
                'longitude' => 110.4167,
            ],
            [
                'name' => 'Dieng Plateau',
                'description' => 'Dataran tinggi vulkanik dengan pemandangan alam yang spektakuler, kawah berwarna-warni, dan candi-candi kuno.',
                'address' => 'Dieng Kulon, Banjarnegara',
                'city' => 'Wonosobo',
                'category' => 'Alam & Petualangan',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
                'rating' => 4.7,
                'total_reviews' => 1200,
                'entrance_fee' => 15000,
                'opening_hours_start' => '05:00:00',
                'opening_hours_end' => '18:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Warung', 'Penginapan'],
                'latitude' => -7.2069,
                'longitude' => 109.9081,
            ],
            [
                'name' => 'Keraton Surakarta',
                'description' => 'Istana kerajaan Surakarta yang masih berfungsi hingga kini, menyimpan kekayaan budaya dan sejarah Jawa.',
                'address' => 'Jl. Slamet Riyadi, Keprabon',
                'city' => 'Surakarta',
                'category' => 'Sejarah & Budaya',
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600',
                'rating' => 4.4,
                'total_reviews' => 950,
                'entrance_fee' => 12000,
                'opening_hours_start' => '09:00:00',
                'opening_hours_end' => '15:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Museum', 'Toko Souvenir'],
                'latitude' => -7.5755,
                'longitude' => 110.8243,
            ],
            [
                'name' => 'Taman Nasional Karimunjawa',
                'description' => 'Kepulauan tropis dengan keanekaragaman hayati laut yang luar biasa, pantai berpasir putih, dan terumbu karang yang indah.',
                'address' => 'Kepulauan Karimunjawa',
                'city' => 'Jepara',
                'category' => 'Pantai & Bahari',
                'image' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600',
                'rating' => 4.9,
                'total_reviews' => 3200,
                'entrance_fee' => 25000,
                'opening_hours_start' => '06:00:00',
                'opening_hours_end' => '18:00:00',
                'facilities' => ['Dermaga', 'Toilet', 'Warung', 'Penginapan', 'Penyewaan Alat Snorkeling'],
                'latitude' => -5.8408,
                'longitude' => 110.4203,
            ],
            [
                'name' => 'Pantai Parangtritis',
                'description' => 'Pantai legendaris dengan ombak besar, gumuk pasir, dan sunset yang memukau. Terkenal dengan legenda Nyi Roro Kidul.',
                'address' => 'Parangtritis, Kretek',
                'city' => 'Bantul',
                'category' => 'Pantai & Bahari',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
                'rating' => 4.3,
                'total_reviews' => 2100,
                'entrance_fee' => 5000,
                'opening_hours_start' => '05:00:00',
                'opening_hours_end' => '19:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Warung', 'ATV', 'Andong'],
                'latitude' => -8.0252,
                'longitude' => 110.3307,
            ],
            [
                'name' => 'Kota Lama',
                'description' => 'Kawasan bersejarah dengan bangunan kolonial Belanda yang ikonik, pusat wisata foto dan kuliner di Semarang.',
                'address' => 'Kota Lama, Semarang',
                'city' => 'Semarang',
                'category' => 'Sejarah & Budaya',
                'image' => '',
                'rating' => 4.6,
                'total_reviews' => 1100,
                'entrance_fee' => 0,
                'opening_hours_start' => '07:00:00',
                'opening_hours_end' => '22:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Cafe', 'Toko Souvenir'],
                'latitude' => -6.9667,
                'longitude' => 110.4281,
            ],
            [
                'name' => 'Pantai Menganti',
                'description' => 'Pantai pasir putih dengan tebing hijau dan pemandangan laut selatan yang menakjubkan di Kebumen.',
                'address' => 'Desa Karangduwur, Ayah',
                'city' => 'Kebumen',
                'category' => 'Pantai & Bahari',
                'image' => '',
                'rating' => 4.7,
                'total_reviews' => 900,
                'entrance_fee' => 10000,
                'opening_hours_start' => '06:00:00',
                'opening_hours_end' => '18:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Warung', 'Gazebo'],
                'latitude' => -7.7711,
                'longitude' => 109.4067,
            ],
            [
                'name' => 'Owabong Waterpark',
                'description' => 'Taman rekreasi air terbesar di Banyumas, cocok untuk keluarga dan anak-anak.',
                'address' => 'Jl. Raya Owabong No.1, Bojongsari',
                'city' => 'Banyumas',
                'category' => 'Taman Rekreasi',
                'image' => '',
                'rating' => 4.5,
                'total_reviews' => 1300,
                'entrance_fee' => 40000,
                'opening_hours_start' => '08:00:00',
                'opening_hours_end' => '17:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Kolam Renang', 'Food Court'],
                'latitude' => -7.3972,
                'longitude' => 109.2647,
            ],
            [
                'name' => 'Umbul Manten & Umbul Cokro (OMAC)',
                'description' => 'Wisata air alami dengan kolam jernih, pemandangan asri, dan wahana seru di Klaten.',
                'address' => 'Umbul Cokro, Cokro, Tulung',
                'city' => 'Klaten',
                'category' => 'Alam & Petualangan',
                'image' => '',
                'rating' => 4.6,
                'total_reviews' => 800,
                'entrance_fee' => 15000,
                'opening_hours_start' => '07:00:00',
                'opening_hours_end' => '17:00:00',
                'facilities' => ['Parkir', 'Toilet', 'Kolam Renang', 'Gazebo'],
                'latitude' => -7.6531,
                'longitude' => 110.6242,
            ],
        ];

        foreach ($tourismData as $tourism) {
            Tourism::create($tourism);
        }
    }
}